import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Sidebar from "./components/sidebar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex max-w-4xl container mx-auto gap-[4rem]">
          <Sidebar />
          <div className="pt-[4rem]">
            <div>{children}</div>
            <div className="py-[2rem]">
              <p className="text-center text-gray-500">
                © {new Date().getFullYear()} Nipun Perera
              </p>
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
